"""added created_at coloumn

Revision ID: 0655057dc2ac
Revises: 3f286d4b1259
Create Date: 2026-01-02 00:01:57.461335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0655057dc2ac'
down_revision: Union[str, Sequence[str], None] = '3f286d4b1259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))

    op.alter_column('documents', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'analysis',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="CASE WHEN analysis = '' OR analysis IS NULL THEN '{}'::json ELSE analysis::json END")
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.alter_column('documents', 'analysis',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###
