"""add_cost_and_hash_columns

Revision ID: 1a0190db0985
Revises: 3886c5b80ef6
Create Date: 2026-04-23 13:19:49.350261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0190db0985'
down_revision: Union[str, Sequence[str], None] = '3886c5b80ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.add_column('users', sa.Column('total_tokens', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_tokens')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
