name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. LINT JOB: Checks for PEP8 and code quality
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Ruff
        run: pip install ruff
      - name: Lint with ruff
        run: ruff check .

  # 2. TEST JOB: Runs pytest cases
  test:
    needs: lint 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install
      - name: Run Pytest
        env:
          ENV: testing
          DATABASE_URL: postgresql+asyncpg://user:password@localhost:5432/test_db
          DATABASE_SYNC_URL: postgresql://user:password@localhost:5432/test_db
          DB_PORT: 5432
          REDIS_URL: redis://localhost:6379/0
          REDIS_PORT: 6379
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          STORAGE_TYPE: "local"
          AI_PROVIDER: "mock"
        run: poetry run pytest